name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches: [ main ]
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" "#chapters/vendor/**"
