name: Welcome First-Time Contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Thanks for opening your first issue!
            Please be sure you've read CONTRIBUTING.md and, if proposing content, looked at pattern-template.md.
          pr-message: |
            🎉 Thanks for your first pull request!
            A maintainer will review for technical accuracy and style. Make sure you've filled out the PR checklist.
